#!/bin/sh
#
# This preprocesses a set of word lists into a suitable form for input
# into cracklib-packer
#
LC_ALL=C
export LC_ALL
gzip -cdf "$@" |
    grep -a -E -v '^.{32,}$' |
    tr '[:upper:]' '[:lower:]' |
    tr -cd '\n[:graph:]' |
    sort -u
